### ISSUE TITLE
Invalid IfcCurveSegment.Transition not detected

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/validate#7]
Based on CT 4.1.7.1.1 and its subsections, IfcCompositeCurve and it's subclasses IfcGradientCurve and IfcSegmentedReferenceCurve are open curves. This inference is justified from the statement:

> A zero-length segment shall be added, at the end of the list of segments for [IfcAlignmentSegment](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcAlignmentSegment.htm).DesignParameters.
> If the geometry definition is also present, then each of the zero-length segments shall have a [IfcCurveSegment](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcCurveSegment.htm) counterpart - of length zero.

If the curve is not open, there is no need for the required zero length segment because the end of the last segment is defined by the start of the first segment.

From that reasoning, the Formal Proposition of 8.9.3.20.4 states

> No transition code should be Discontinuous, except for the last code of an open curve

Which would then required that IfcCurveSegment.Transtion == IfcTransitionCode.DISCONTINUOUS for the last segment.

The attached file has IfcCompositeCurve and IfcGradientCurve with the transition code of the last segments set to CONTINUOUS and it is not detected by the validation service as an error.

[IFC_Alignment4_Br1.ifc.txt](https://github.com/buildingSMART/validate/files/13198973/IFC_Alignment4_Br1.ifc.txt)

**Comment by civilx64** [comment]
@RickBrice I agree and this is in the backlog for alignment validation work currently underway.  More specifically, it will be implemented within the rule checking portion of the validation service. I propose the following:

1. This requirement be captured as a new rule `ALG001` as it deals with the geometry aspect of an alignment
2. A second requirement of `IfcCurveSegment.Length == 0.000` be added in addition to `IfcCurveSegment.Transition == IfcTransitionCode.DISCONTINUOUS`.
3. Your example file above will be used as a `fail` example for testing / confirming that the validation service flags this as an error.
4. We close this issue here in the validation repo and open a new one in [ifc-gherkin-rules](https://github.com/buildingSMART/ifc-gherkin-rules/issues/)

@evandroAlfieri if you agree I will proceed as proposed.  Pinging @berlotti and @aothms as well for visibility.

**Comment by RickBrice** [comment]
@civilx64 if I may, related but slightly off topic - there seems to be a need for clarity of specification and validation rule that IfcCompositeCurve (and its subtypes) .Segment attribute be of one IfcSegment subtype instead of a mix of IfcCompositeCurveSegment and IfcCurveSegment. IfcCompositeCurve can technically be composed from both IfcSegment subtypes because both are trimmed from a ParentCurve albeit by different mechanics. CT 4.1.7.1.1 and subsections define composition using exclusively IfcCurveSegment when IfcCompositeCurve and subtypes are for the representation of alignments. Additionally, the Ifc4.0.2 specification requires IfcCompositeCurve.Segment to be of type IfcCompositeCurveSegment. I assume this construct was not intended to be changed in 4.3.

**Comment by evandroAlfieri** [comment]
Good stuff here. I see the discussion progressed in https://github.com/IfcOpenShell/IfcOpenShell/pull/3945 and resulted in a new rule in our backlog - tracked by https://github.com/buildingSMART/ifc-gherkin-rules/issues/105.
@RickBrice @civilx64 if you both agree, I'd close this issue here and move on from the two above. Ok?

**Comment by civilx64** [comment]
Agreed!

**Comment by RickBrice** [comment]
Agreed!
